
CREATE TABLE Tariff (ID int PRIMARY KEY AUTO_INCREMENT, tariff varchar(50) NOT NULL);

CREATE TABLE Balance ( ID int PRIMARY KEY AUTO_INCREMENT, amount INT NOT NULL);

CREATE TABLE User (ID int PRIMARY KEY AUTO_INCREMENT, name varchar(50) NOT NULL, balance_id INTEGER NOT NULL, tariff_id INTEGER NOT NULL, FOREIGN KEY (balance_id) REFERENCES Balance(ID), FOREIGN KEY (tariff_id) REFERENCES Tariff(ID));
